export const TRANSACTION_LIST_REQUEST = 'PRO/TRANSACTION_LIST_REQUEST';
export const TRANSACTION_LIST_FAILURE = 'PRO/TRANSACTION_LIST_FAILURE';
export const TRANSACTION_LIST_SUCCESS = 'PRO/TRANSACTION_LIST_SUCCESS';
export const REFUND_TRANSACTION_REQUEST = 'PRO/REFUND_TRANSACTION_REQUEST';
export const REFUND_TRANSACTION_FAILURE = 'PRO/REFUND_TRANSACTION_FAILURE';
export const REFUND_TRANSACTION_SUCCESS = 'PRO/REFUND_TRANSACTION_SUCCESS';
